# Database(PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Log
logging.level.root=info

# Multipart
spring.servlet.multipart.location=/tmp/uploads

# Upload
document.upload-dir=/tmp/uploads

# OpenAI
openai.api.key=${OPENAI_API_KEY}
