CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moddate TIMESTAMP(6) NOT NULL,
    regdate TIMESTAMP(6) NOT NULL,
    email VARCHAR(255) NOT NULL,
    nickname VARCHAR(20) NOT NULL,
    password VARCHAR(100) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moddate TIMESTAMP(6) NOT NULL,
    regdate TIMESTAMP(6) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    extracted_text TEXT,
    file_size BIGINT NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT uk_documents_stored_filename UNIQUE (stored_filename),
    CONSTRAINT fk_documents_user_id
	FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT ck_documents_status
        CHECK (
            status IN (
                'UPLOADED',
                'PROCESSING',
                'COMPLETED',
                'FAILED'
            )
        )
);

CREATE TABLE document_ai_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moddate TIMESTAMP(6) NOT NULL,
    regdate TIMESTAMP(6) NOT NULL,
    content TEXT NOT NULL,
    model VARCHAR(255),
    total_tokens INTEGER,
    type VARCHAR(255) NOT NULL,
    document_id BIGINT NOT NULL,
    CONSTRAINT fk_document_ai_results_document_id
        FOREIGN KEY (document_id)
        REFERENCES documents (id),
    CONSTRAINT ck_document_ai_results_type
        CHECK (
            type IN (
                'SUMMARY'
            )
        )
);
