CREATE TABLE document_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moddate TIMESTAMP(6) NOT NULL,
    regdate TIMESTAMP(6) NOT NULL,
    document_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    chunk_index INTEGER NOT NULL,
    CONSTRAINT fk_document_chunks_document_id
        FOREIGN KEY (document_id)
        REFERENCES documents (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_document_chunks_document_id
ON document_chunks(document_id);